dev_upload_folder:
	@echo "Running backupr-cli dev"
	@java -jar -Dspring.profiles.active=dev target/backupr-cli-0.0.1-SNAPSHOT.jar -u ./src/test/resources/

dev_download_file:
	@echo "Running backupr-cli dev"
	@java -jar -Dspring.profiles.active=dev target/backupr-cli-0.0.1-SNAPSHOT.jar -d filesystem/file1.txt
